# Generated by Django 4.1.8 on 2023-04-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image",
        ),
        migrations.AlterField(
            model_name="image",
            name="height",
            field=models.PositiveSmallIntegerField(verbose_name="Height"),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="image",
            name="width",
            field=models.PositiveSmallIntegerField(verbose_name="Width"),
        ),
    ]
