# Generated by Django 3.2.14 on 2022-07-21 08:09

from django.db import migrations


def create_anon_user(apps, schema_editor):
    User = apps.get_model("users", "User")

    User.objects.create(
        is_staff=False,
        is_active=False,
        email="anon@anon.com",
        password="#",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_anon_user),
    ]
